---
image: Visual Studio 2017

environment:
  matrix:
  - PYTHON: C:\Python36

build: off

install:
- set PATH=C:\Python36\Scripts;%PATH%
- '%PYTHON%\python.exe -m pip install PyInstaller wxPython pypiwin32'

before_test:
- '%PYTHON%\python.exe -m pip install tox'

test_script:
- '%PYTHON%\python.exe -m tox -e flake8'
- '%PYTHON%\python.exe -m tox -e py36'

after_test:
- '%PYTHON%\python.exe setup.py clean bundle'

artifacts:
- path: dist\PythonTurtle.exe

on_success:
- dir dist
