---
resources:
- name: pythonturtle_repo
  type: gitRepo
  integration: github
  buildOnPullRequest: true
  pointer:
    sourceName: cool-RR/PythonTurtle

jobs:

- name: windows_build
  type: runSh
  allowPublicAccess: true
  runtime:
    nodePool: dyn_win16
  steps:
  - IN: pythonturtle_repo
  - TASK:
      name: System_info
      script:
      - systeminfo
      - Get-Process
      - pushd $(shipctl get_resource_state "pythonturtle_repo")
      - choco install -y python --version 3.6.3
      - 'C:\Python36\python.exe --version'
  - TASK:
      name: Prerequisites
      script:
      - 'C:\Python36\python.exe -m pip install PyInstaller wxPython pypiwin32'
  - TASK:
      name: Lint
      script:
      - 'C:\Python36\python.exe -m tox -e flake8'
      - 'C:\Python36\python.exe -m tox -e pylint'
  - TASK:
      name: Test
      script:
      - 'C:\Python36\python.exe -m tox -e py36'
  - TASK:
      name: Windows_exe
      script:
      - 'C:\Python36\python.exe setup.py clean bundle'

- name: push_artifacts
  type: runSh
  allowPublicAccess: true
  runtime:
    nodePool: dyn_win16
  steps:
  - IN: windows_build
  - TASK:
      name: push_artifacts_somewhere
      script:
      - systeminfo
      - dir dist
