"""
This is a setup.py script generated by py2applet

Usage:
    python py2app_setup.py py2app
"""

import os
from setuptools import setup
from pythonturtlebuildtools import smart_join, data_files

cwd = os.getcwd()
root_dir = smart_join(cwd, "..", "..")
src_dir = smart_join(root_dir, "src")
build_dir = smart_join(cwd, "osx_build")
dist_dir = smart_join(root_dir, "osx_dist")
resources_dir = smart_join(src_dir, "resources")
osx_resources_dir = smart_join(cwd, "osx_resources")
path_to_script = smart_join(src_dir, "pythonturtle.py")
path_to_icon = smart_join(resources_dir, "icon.icns")
path_to_plist = smart_join(osx_resources_dir, "Info.plist")

py2app_options = {
    'arch': 'i386',
    'argv_emulation': True,
    'bdist_base': build_dir,
    'dist_dir': dist_dir,
    'iconfile': path_to_icon,
    'includes': 'wx',
    'plist': path_to_plist,
}

setup(
    app=[path_to_script],
    data_files=data_files(resources_dir),
    options={'py2app': py2app_options},
    setup_requires=['py2app', 'wxPython'],
)