"""
This is a setup.py script generated by py2applet

Usage:
    python py2app_setup.py py2app
"""
import os
from setuptools import setup
from pythonturtlebuildtools import get_data_files, get_joined_path

# pylint: disable=invalid-name
cwd = os.getcwd()
root_dir = get_joined_path(cwd, "..", "..")
src_dir = get_joined_path(root_dir, "src")
build_dir = get_joined_path(cwd, "osx_build")
dist_dir = get_joined_path(root_dir, "osx_dist")
resources_dir = get_joined_path(src_dir, "resources")
osx_resources_dir = get_joined_path(cwd, "osx_resources")
path_to_script = get_joined_path(src_dir, "pythonturtle.py")
path_to_icon = get_joined_path(resources_dir, "icon.icns")
path_to_plist = get_joined_path(osx_resources_dir, "Info.plist")

resource_files_list = get_data_files(resources_dir)
py2app_options = {
    'arch': 'i386',
    'argv_emulation': True,
    'bdist_base': build_dir,
    'dist_dir': dist_dir,
    'iconfile': path_to_icon,
    'includes': 'wx',
    'plist': path_to_plist,
}

setup(
    app=[path_to_script],
    data_files=resource_files_list,
    options={'py2app': py2app_options},
    setup_requires=['py2app', 'wxPython'],
)
