name: Build binaries

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  linux-elf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: sudo apt-get install libsdl2-2.0-0
    - run: python -m pip install pyinstaller
    - run: python -m pip install --find-links ${WHEELS} wxPython
      env:
        WHEELS: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04
    - run: python setup.py clean bundle
    - uses: actions/upload-artifact@v2
      with:
        name: PythonTurtle
        path: ${{ github.workspace }}/dist/PythonTurtle

  macos-app:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python -m pip install pyinstaller wxPython
    - run: python setup.py clean bundle
    - run: rm ${{ github.workspace }}/dist/PythonTurtle
    - uses: actions/upload-artifact@v2
      with:
        name: PythonTurtle.app
        path: ${{ github.workspace }}/dist/

  windows-exe:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: python -m pip install pyinstaller wxPython
    - run: python setup.py clean bundle
    - uses: actions/upload-artifact@v2
      with:
        name: PythonTurtle.exe
        path: ${{ github.workspace }}\dist\PythonTurtle.exe
