name: Build Linux ELF

on:
  push:
    tags:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: sudo apt-get install libsdl2-2.0-0
    - run: python -m pip install pyinstaller
    - env:
        URL: https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04
      run: python -m pip install --find-links ${URL} wxPython
    - run: python setup.py clean bundle
    - run: chmod +x /home/runner/work/PythonTurtle/PythonTurtle/dist/PythonTurtle
    - uses: actions/upload-artifact@v2
      with:
        name: PythonTurtle for Linux
        path: /home/runner/work/PythonTurtle/PythonTurtle/dist/PythonTurtle
