name: Publish binaries and Python package

on:
  push:
    tags:
    - "*"

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install prerequisites
      run: python -m pip install --upgrade pip setuptools twine wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
